name: 名称：Build SU
on:
  push:
    branches: [分支：["next"]"next" ]
    paths:
      - '.github/workflows/build-su.yml'
      - 'userspace/su/**'
      - 'scripts/ksunextbot.py'
  pull_request:
    branches: [分支：["next"]"next" ]
    paths:
      - 'userspace/su/**'
jobs:
  build-su:
    name: 名称：生成用户空间su
    runs-on: run-on:ubuntu-latest
    steps:
    - uses: -使用：操作/结帐@v4
      with:
        fetch-depth: 0
    - name: -名称：安装程序需要_上载
      id: ID:need_upload
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          echo "UPLOAD=true" >> $GITHUB_OUTPUT
        else
          echo "UPLOAD=false" >> $GITHUB_OUTPUT
        fi
    - name: -名称：Build su
      working-directory: 工作目录：./userspace/su
      run: 运行：$ANDROID_NDK/ndk-build
    - name: -名称：上载生成对象
      uses: 用法：操作/上载工件@v4
      with:
        name: 名称：su
        path: 路径：./userspace/su/libs
